### PR TITLE
Allow package overrides

### LINKED ISSUE #35: Let nix users specify the rust platform?
Integrating dsc in my nix flake (which forces users to pin all revisions of all software), I get an error:

```
error: in pure evaluation mode, 'fetchTarball' requires a 'sha256' argument
```

which I'm tracing back to https://github.com/docspell/dsc/blob/master/nix/rust-platform.nix#L3-L4, where fetchTarball is invoked in a way that prevents hermetic encapsulation. I think it's fine to provide this as a default for non-pinned builds, but it would be very nice if we were able to override the rustPlatform argument to the package.

### PR DESCRIPTION
**Pull request by antifuchs**
I believe this fixes #35.

Still testing this, but I believe this is the smallest unit of change we need to make to allow dsc to be integrated in a hermetic build.

### CODE REVIEW

**Comment by antifuchs** [comment]
Looking at this some more I think I'll also have to override the `cargoSha256` when passing a different version of the rust toolchain, as that varies /-:

**Comment by eikek** [comment]
> Looking at this some more I think I'll also have to override the `cargoSha256` when passing a different version of the rust toolchain, as that varies /-:

Yes, this is a bit annoying. As soon as someone changes the cargo lock file, this hash is "out of date" and must be fixed manually. I'm a bit surprised that this also changes with a different rust platform, I had the impression that this hash is only representing the dependency crates. I don't know a better way either than to provide this hash as an argument :/

**Comment by antifuchs** [comment]
I strongly prefer [naersk](https://github.com/nix-community/naersk) for just this reason: It uses the Cargo.lock directly, and just does not require that checksum. If you're interested I can try and submit another PR using naersk (the package definition is much shorter that way), but I guess for now I'll back out the change to the package definition entirely; only allowing users to set a `services.dsc-watch.package`  option will be enough to let me set it up in my system configuration (:

**Comment by eikek** [comment]
Oh interesting tip, thank you! I need to find time to look more into this (naersk and flakes, too…). If you find time to convert this setup to be simpler and shorter, I'm all for it! Otherwise do whatever it takes to work in your setup. I'm sure I can easily adopt mine then. All this rusty stuff is very new to me :-)

**Comment by antifuchs** [comment]
Glad to - I stumbled across a few more things in the module too, hope to get something submitted to straighten that out too (:

**Pull request merged**
