### PR TITLE
[nix] migrate flake to flake-parts

### PR DESCRIPTION
**Pull request by VTimofeenko**
This set of changes effectively replaces flake-utils with flake-parts.

The changes:

- Original flake.nix did not work with `nix run` complaining that the app is not a derivation
- Building the package is delegated to purpose-built "naersk" utility. The end-result is the same, but there is less code to maintain now.
- [minor] Original flake-utils machinery is more clunky and raises deprecation warnings for defaultApp/defaultPackage. Flake-parts is more concise when generating per-system default attributes like packages.x86_64-linux.default

Some of the original build inputs (rust-analysis and rls) are not (yet?) replicated into the new flake. Whether they need to be - TBD.

### CODE REVIEW

**Comment by VTimofeenko** [comment]
Hi! As discussed in gitter - making a PR for the new flake. 

Some things I wanted to discuss:

1. Should `nix/dsc.nix` be kept? It's effectively merged into `flake.nix` with naersk building the package
2. `nix/module.nix` contains an implementation of `dsc-watch`. Should that perhaps be merged into the docspell flake?
3. Should `nix/tests/` test harness be integrated in flake? One way to do it is to import the docspell flake and re-use the test nixosConfiguration

Points 2 and 3 should probably be separate PRs if they are to be implemented

**Comment by eikek** [comment]
Hi @VTimofeenko thanks a lot for this! To the questions:

1. I think we can ditch this then!
2. I think it is better kept here, as it is an application of dsc and not docspell but perhaps it can be better integrated into the flake?
3. Yes, I'm all for it. The current state is only due to my inability to have it better; and I'm fine with starting a script once in a while.

**Comment by VTimofeenko** [comment]
Great! Looks like the PR is ready to merge then.

1. Done, force-pushed
2. Agreed, I created #275  - can you assign it to me please?
3. Created #276 - can you also assign that issue to me?

**Comment by eikek** [comment]
So great! 💯

**Pull request merged**
